[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.0"

[[constraint]]
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"